CREATE TABLE IF NOT EXISTS `T_CAINFO` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ca_id` VARCHAR(26) NOT NULL,
  `password` VARCHAR(255) NOT NULL DEFAULT '',
  `created` VARCHAR(19) NOT NULL DEFAULT '1970-01-01T09:00:00',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_cainfo_ca_id` (`ca_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;